title: "Injoy Decor"
description: "Professional Decorative Wall Material Manufacturer"
url: "https://你的用户名.github.io"
baseurl: "/minimal-mistakes"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache


locale: "en-US"

author:
  name: "Injoy Decor"
  avatar:
  bio: "Manufacturer of Marble Wall Stickers, 3D Foam Wallpaper and Acoustic Panels"

footer:
  links: []

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
